color0 #162a3c
color1 #fd4663
color2 #67a9e4
color3 #5c5fd6
color4 #9766cc
color5 #93c2ec
color6 #9698e9
color7 #f2f2f3
color8 #5f6a73
color9 #fd4663
color10 #67a9e4
color11 #5c5fd6
color12 #9766cc
color13 #93c2ec
color14 #9698e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #000000
background            #000000
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #162a3c
active_border_color   #67a9e4
inactive_border_color #001223
url_color             #67a9e4

active_tab_foreground   #14191e
active_tab_background   #67a9e4
inactive_tab_foreground #afb3b6
inactive_tab_background #001223
cursor_trail_color      #afb3b6
