color0 #292929
color1 #fd4663
color2 #e46767
color3 #d65c5c
color4 #cc6666
color5 #ec9393
color6 #e99696
color7 #f3f2f2
color8 #696969
color9 #fd4663
color10 #e46767
color11 #d65c5c
color12 #cc6666
color13 #ec9393
color14 #e99696
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #000000
background            #000000
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #292929
active_border_color   #e46767
inactive_border_color #101011
url_color             #e46767

active_tab_foreground   #251818
active_tab_background   #e46767
inactive_tab_foreground #b6afaf
inactive_tab_background #101011
cursor_trail_color      #b6afaf
